### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by ghost** [0xFounders/imgui-win32#1]
Original source: https://github.com/super-continent/imgui-impl-win32-rs from @super-continent

**Comment by ohchase** [comment]
Wait are you a bot or a real account lol, your name confuses me.
Regardless, thank you for the original source that's exactly the one I worked off of!
I'll properly add credits now and send the author a ping to see if they're okay with the library staying up

**Comment by ohchase** [comment]
I actually have no idea how to send a message to a person on github, @super-continent feel free to chime in if this sends you a notifications - thanks chase

**Comment by super-continent** [comment]
yes, this appears to be my code, it appears to have been migrated to windows-rs with some additional changes though, i dont care too much about what happens to the code for this because it was a very small port of an imgui impl file. credit would be appreciate though
